<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle()?>
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="/js/jquery.min.js"></script>
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!--<link rel="stylesheet/less" href="/lib/bootstrap.less"><script src="/js/less-1.1.5.min.js"></script> -->
        <script src="/js/bootstrap-dropdown.js"></script>
        <script src="/js/global.js"></script>
        <link href="/css/global.css" rel="stylesheet">


        <!-- Le styles -->
        <style type="text/css">
            body {
                padding-top: 60px;
            }
        </style>

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="images/favicon.ico">
        <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
    </head>

    <body>

        <?=$this->render('_topbar.phtml');?>

        <div class="container-fluid">
            
            <?=$this->sideBar?$this->render('_sidebar.phtml'):''?>
            
            <div class="content<?=$this->sideBar?' use-sidebar':''?>">

                <?=$this->layout()->content?>

                <?=$this->render('_footer.phtml');?>
            </div>
        </div>

    </body>
</html>